### ISSUE TITLE
个推通道消息(push_message)内容中的payload现在是不是没有用

### ISSUE THREAD

**Issue by sannmizu** [GetuiLaboratory/getui-pushapi-java-client-v2#4]
```java
String title = notice.getTopic().getTopic();
String body = notice.getTitle();
String payload = "自定义数据";
// 设置个推通道通知内容
PushMessage message = new PushMessage();
GTNotification notification = new GTNotification();
notification.setTitle(title);
notification.setBody(body);
notification.setClickType("payload");
notification.setPayload(payload);
notification.setChannelLevel(notice.isImportant() ? "4" : "3");
message.setNotification(notification);
```

click_type设置为payload，按理说就能在通知中携带上payload的数据，但是并没有用，最终收到的payload的内容是`{"title":"xxx","content":"xxx"}`，也就是通知标题和通知内容，被强制设置了，我设置的自定义数据找不到，请问这个接口的payload到底怎么用的

**Comment by sannmizu** [comment]
是不是想传自定义payload只能使用transmission而不是notification

**Comment by smartboat** [comment]
可以用notification+payload实现通知+自定义消息
验证方式：让客户端的同学把接收到的参数全部打印看下或者[个推客户端API](https://docs.getui.com/getui/mobile/android/api/)参见**接收透传消息**说明

**Comment by sannmizu** [comment]
> 可以用notification+payload实现通知+自定义消息
> 验证方式：让客户端的同学把接收到的参数全部打印看下或者[个推客户端API](https://docs.getui.com/getui/mobile/android/api/)参见**接收透传消息**说明

谢谢回答，客户端获取出来的结果中payload不是我在发起推送接口设置的payload，而是{"title":"xxx","content":"xxx"}这种格式的数据，即通知的标题和内容，我自己设置的payload会被强制覆写。我现在已经使用intent的方式来实现功能了，intent也能够携带上数据

**Comment by smartboat** [comment]
服务端字段名称传到客户端，payload字段内容会被加密，要调用个推SDK接口获取

**Comment by sannmizu** [comment]
> 服务端字段名称传到客户端，payload字段内容会被加密，要调用个推SDK接口获取

原来如此，那我了解了
