### ISSUE TITLE
这版的sdk发给ios的离线消息收不到

### ISSUE THREAD

**Issue by loncool** [GetuiLaboratory/getui-pushapi-java-client-v2#6]
//根据cid进行单推
        PushDTO<Audience> pushDTO = new PushDTO<Audience>();
        // 设置推送参数
        pushDTO.setRequestId(System.currentTimeMillis() + "");

        PushMessage pushMessage = new PushMessage();
        //透传消息
        pushMessage.setTransmission(transmission);

        pushDTO.setPushMessage(pushMessage);

        //厂商通道消息内容

        //推送通知消息内容
        Aps aps = new Aps();
        //1表示静默推送(无通知栏消息)，静默推送时不需要填写其他参数。
        //苹果建议1小时最多推送3条静默消息
        aps.setContentAvailable(1);
        aps.setSound("com.gexin.ios.silence");

        IosDTO iosDTO = new IosDTO();
        iosDTO.setAps(aps);
        iosDTO.setType("notify");
        iosDTO.setPayload(transmission);

        PushChannel pushChannel = new PushChannel();
        pushChannel.setIos(iosDTO);
        pushDTO.setPushChannel(pushChannel);

        // 设置接收人信息
        Audience audience = new Audience();
        audience.addCid(cid);
        pushDTO.setAudience(audience);

        // 进行cid单推
        ApiResult<Map<String, Map<String, String>>> apiResult = getClient().pushToSingleByCid(pushDTO);

**Comment by java-aodeng** [comment]
我也遇到ios收不到消息的问题了，大佬怎么解决的

**Comment by java-aodeng** [comment]
# 这版的sdk发给ios的离线消息收不到 解决方案，琢磨了一会自己解决了，ios需要需要配置推送条件 和 厂商通道消息
```
//----------》解决ios 收不到消息的问题，需要配置推送条件 和 厂商通道消息内容《----------
        //配置推送条件
        Strategy strategy=new Strategy();
        strategy.setDef(1);
        strategy.setIos(4);
        strategy.setSt(1);

        Settings settings=new Settings();
        settings.setStrategy(strategy);
        pushDTO.setSettings(settings);

        //推送通知消息内容
        Alert alert=new Alert();
        alert.setTitle("test----");//标题
        alert.setBody("this is test body");//内容

        Aps aps = new Aps();
        //1表示静默推送(无通知栏消息)，静默推送时不需要填写其他参数。
        //苹果建议1小时最多推送3条静默消息
        aps.setContentAvailable(0);
        aps.setSound("default");
        aps.setAlert(alert);

        IosDTO iosDTO = new IosDTO();
        iosDTO.setAps(aps);
        iosDTO.setType("notify");

        PushChannel pushChannel = new PushChannel();
        pushChannel.setIos(iosDTO);
        pushDTO.setPushChannel(pushChannel);//添加厂商通道消息
        //《-------------------------解决ios...代码end
```

**Comment by loncool** [comment]
原因是客户端接的sdk不是最新导致的。
